"""empty message

Revision ID: d8c5c7097172
Revises: 32d397fdffb4
Create Date: 2022-05-14 01:00:09.270617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c5c7097172'
down_revision = '32d397fdffb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'created_date')
    # ### end Alembic commands ###
